name: eandu
recipe: drupal7
config:
  php: '8.1'
  drush: '8.4.10'
  webroot: docroot
proxy:
  mailhog:
    - mail.eandu.lndo.site
services:
  database:
    creds:
      user: database
      password: database
      database: database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
tooling:
  drush:
    service: appserver
    cmd:
      - 'drush --root=/app/docroot'
